
hazelcast.cluster.name=${HAZELCAST_CLUSTER_NAME:hazelcast-cluster-demo}

hazelcast.near.cache=employeeMap


hazelcast.client.connection.attemt.limit=1000000000
hazelcast.client.connection.attemt.period = 10000
hazelcast.client.smart.routing=true
hazelcast.client.redo.operation = true
hazelcast.client.connection.timeout=1000000

hazelcast.client.group.name=ATM-HZ

hazelcast.client.instance.name=atm-server-client
hazelcast.client.statistics.enabled=true

hazelcast.client.async-start=false
hazelcast.client.reconnect-mode=ON

hazelcast.discovery.enabled=false