spring.application.name=Employee
spring.datasource.url=jdbc:postgresql://localhost:5432/Employee
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate auto ddl should be none (Liquibase will manage schema)
spring.jpa.hibernate.ddl-auto=none

# Show SQL (optional)
spring.jpa.show-sql=true
