version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: employee_db
    restart: always
    environment:
      POSTGRES_DB: Employee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
